# Class Notes 1/11/24 #

### An Object-Oriented Perceptron ###

In [11]:
import numpy as np

class Perceptron:
    """Perceptron classifier.

    Parameters
    ------------
    eta : float
      Learning rate (between 0.0 and 1.0)
    n_iter : int
      Passes over the training dataset.
    random_state : int
      Random number generator seed for random weight
      initialization.

    Attributes
    -----------
    w_ : 1d-array
      Weights after fitting.
    b_ : Scalar
      Bias unit after fitting.
    errors_ : list
      Number of misclassifications (updates) in each epoch.

    """
    def __init__(self, eta=0.01, n_iter=50, random_state=1):
        self.eta = eta
        self.n_iter = n_iter
        self.random_state = random_state

    def fit(self, X, y):
        """Fit training data.

        Parameters
        ----------
        X : {array-like}, shape = [n_examples, n_features]
          Training vectors, where n_examples is the number of examples and
          n_features is the number of features.
        y : array-like, shape = [n_examples]
          Target values.

        Returns
        -------
        self : object

        """
        rgen = np.random.RandomState(self.random_state)
        self.w_ = rgen.normal(loc=0.0, scale=0.01, size=X.shape[1])
        self.b_ = np.float_(0.)
        
        self.errors_ = []

        for _ in range(self.n_iter):
            errors = 0
            for xi, target in zip(X, y):
                update = self.eta * (target - self.predict(xi))
                self.w_ += update * xi
                self.b_ += update
                errors += int(update != 0.0)
            self.errors_.append(errors)
        return self

    def net_input(self, X):
        """Calculate net input"""
        return np.dot(X, self.w_) + self.b_

    def predict(self, X):
        """Return class label after unit step"""
        return np.where(self.net_input(X) >= 0.0, 1, 0)

In [12]:
data = np.genfromtxt('jan11data.csv',delimiter=',')

In [13]:
data

array([[-1.84238004,  1.97394517,  1.        ],
       [-2.98921685,  2.6726499 ,  1.        ],
       [-1.4964729 ,  2.26819417,  1.        ],
       [-2.30311212,  2.12954935,  1.        ],
       [-2.1671905 ,  3.27538149,  1.        ],
       [-1.51056109,  3.07130952,  1.        ],
       [-3.94996259,  1.96830767,  1.        ],
       [-2.56199865,  1.9764674 ,  1.        ],
       [-2.57156931,  1.14506803,  1.        ],
       [-2.05263125,  1.06656843,  1.        ],
       [-3.89742167,  1.61855205,  1.        ],
       [-2.89777976,  2.91820873,  1.        ],
       [-3.62630627,  2.02227248,  1.        ],
       [-3.68295371,  0.71377916,  1.        ],
       [-2.02339907,  0.10986905,  1.        ],
       [-2.10789978,  0.79519064,  1.        ],
       [-2.37070297,  1.27532246,  1.        ],
       [-0.12466844,  0.25415246,  1.        ],
       [-2.09887603,  2.41048992,  1.        ],
       [-2.17283855,  3.66926035,  1.        ],
       [ 2.09364924, -2.23442951, -1.   

In [16]:
X=data[:,0:2]

In [17]:
y = data[:,2]

In [18]:
y

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1.])

In [20]:
y = np.where(y <= 0, 0, 1)

In [21]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
mymodel =Perceptron(.1, 10)

In [25]:
myfittedmodel = mymodel.fit(X,y)

In [26]:
myfittedmodel.predict(X)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
myfittedmodel.predict([1,-4])

array(0)

In [7]:
mydata = np.array([[1,2,3],[4,5,6]])

In [9]:
mydata.shape[0]

2

In [10]:
mydata.shape

(2, 3)